### ISSUE TITLE
unpass count on attendance tab not shown immediately

### ISSUE THREAD

**Issue by miseongk** [luciancah/sejong-attendance#21]
It's shown when refreshing attendance tab.
Needs fix - refreshing to get unpass count when switching the segemented controll.

**Comment by luciancah** [comment]
![3A14BF8D-725B-46E4-AE8F-A4F25F78C78D](https://user-images.githubusercontent.com/8311335/187347008-8e4dd9b3-8155-45a6-8812-b3bc355aa53b.png)

**Comment by luciancah** [comment]
closed #25
